#hibernatin database asamasinda yaptigi validate kontrolunu kapatmak icin bu ayari yaptik
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
             mode: none  data:    web:      pageable:
        default-page-size: 10
        max-page-size: 100  profiles:    active:    - dev     #kendi profilimiz, avantaji: ayni kodun farkli calisma ortamlarinda calismalarinda sagliyor
  servlet:
    multipart:
      max-file-size: 10MB
        
---
spring:  profiles: production
hoaxify:
  upload-path: storage-production
---
spring:  profiles: dev   
hoaxify:  upload-path: storage-dev 